### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ollebergkvist** [felipeplets/esm-examples#5]
I just tried to build using your suggested tsconfig,
but when trying to use the package after the build process I get Error [ERR_MODULE_NOT_FOUND], because the .js extensions have been omitted.

Is there a way to tell typescript to re-add the .js extensions that have been omitted when declaring the paths during build time?

**Comment by felipeplets** [comment]
Hi @ollebergkvist.
Which version of NodeJS are you using? 
Have you used the `--experimental-specifier-resolution=node` as specified in the `package.json` file?

**Comment by felipeplets** [comment]
Closing the issue due to lack of activity.
